// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PointCryptoHandle>>
abstract class PointCryptoHandle implements RustOpaqueInterface {
  /// Add a member to a group using their serialized KeyPackage.
  /// Returns Welcome (for new member) and Commit (for existing members).
  Future<BridgeAddMemberResult> addMember({
    required List<int> groupId,
    required List<int> keyPackageBytes,
  });

  /// Create a new MLS group. Returns the group ID bytes.
  Future<Uint8List> createGroup({required List<int> groupId});

  /// Decrypt ciphertext from a group. Returns plaintext bytes.
  Future<Uint8List> decrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  });

  /// Encrypt plaintext for a group. Returns ciphertext bytes.
  Future<Uint8List> encrypt({
    required List<int> groupId,
    required List<int> plaintext,
  });

  /// Generate a serialized KeyPackage for key exchange.
  /// Upload this to the server so others can add you to groups.
  Future<Uint8List> generateKeyPackage();

  /// Get the number of members in a group.
  Future<BigInt> groupMemberCount({required List<int> groupId});

  /// Check if this instance has joined a specific group.
  bool hasGroup({required List<int> groupId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Create a new MLS crypto instance for this identity (e.g. "alice@point.petalcat.dev").
  static Future<PointCryptoHandle> newInstance({required String identity}) =>
      RustLib.instance.api.crateApiCryptoPointCryptoHandleNew(
        identity: identity,
      );

  /// Process an MLS Commit message to stay in sync with group epoch changes.
  Future<void> processCommit({
    required List<int> groupId,
    required List<int> commitBytes,
  });

  /// Process a Welcome message to join a group. Returns the group ID bytes.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes});
}

/// Result of adding a member to an MLS group.
class BridgeAddMemberResult {
  final Uint8List welcome;
  final Uint8List commit;

  const BridgeAddMemberResult({required this.welcome, required this.commit});

  @override
  int get hashCode => welcome.hashCode ^ commit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAddMemberResult &&
          runtimeType == other.runtimeType &&
          welcome == other.welcome &&
          commit == other.commit;
}
