// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1819868965;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_point',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<BridgeAddMemberResult> crateApiCryptoPointCryptoHandleAddMember({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> keyPackageBytes,
  });

  Future<Uint8List> crateApiCryptoPointCryptoHandleCreateGroup({
    required PointCryptoHandle that,
    required List<int> groupId,
  });

  Future<Uint8List> crateApiCryptoPointCryptoHandleDecrypt({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> ciphertext,
  });

  Future<Uint8List> crateApiCryptoPointCryptoHandleEncrypt({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> plaintext,
  });

  Future<Uint8List> crateApiCryptoPointCryptoHandleGenerateKeyPackage({
    required PointCryptoHandle that,
  });

  Future<BigInt> crateApiCryptoPointCryptoHandleGroupMemberCount({
    required PointCryptoHandle that,
    required List<int> groupId,
  });

  bool crateApiCryptoPointCryptoHandleHasGroup({
    required PointCryptoHandle that,
    required List<int> groupId,
  });

  Future<PointCryptoHandle> crateApiCryptoPointCryptoHandleNew({
    required String identity,
  });

  Future<void> crateApiCryptoPointCryptoHandleProcessCommit({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> commitBytes,
  });

  Future<Uint8List> crateApiCryptoPointCryptoHandleProcessWelcome({
    required PointCryptoHandle that,
    required List<int> welcomeBytes,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PointCryptoHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PointCryptoHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PointCryptoHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<BridgeAddMemberResult> crateApiCryptoPointCryptoHandleAddMember({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> keyPackageBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(keyPackageBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_add_member_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleAddMemberConstMeta,
        argValues: [that, groupId, keyPackageBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleAddMemberConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_add_member",
        argNames: ["that", "groupId", "keyPackageBytes"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointCryptoHandleCreateGroup({
    required PointCryptoHandle that,
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleCreateGroupConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleCreateGroupConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_create_group",
        argNames: ["that", "groupId"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointCryptoHandleDecrypt({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleDecryptConstMeta,
        argValues: [that, groupId, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleDecryptConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_decrypt",
        argNames: ["that", "groupId", "ciphertext"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointCryptoHandleEncrypt({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> plaintext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(plaintext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleEncryptConstMeta,
        argValues: [that, groupId, plaintext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleEncryptConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_encrypt",
        argNames: ["that", "groupId", "plaintext"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointCryptoHandleGenerateKeyPackage({
    required PointCryptoHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleGenerateKeyPackageConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiCryptoPointCryptoHandleGenerateKeyPackageConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_generate_key_package",
        argNames: ["that"],
      );

  @override
  Future<BigInt> crateApiCryptoPointCryptoHandleGroupMemberCount({
    required PointCryptoHandle that,
    required List<int> groupId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleGroupMemberCountConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleGroupMemberCountConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_group_member_count",
        argNames: ["that", "groupId"],
      );

  @override
  bool crateApiCryptoPointCryptoHandleHasGroup({
    required PointCryptoHandle that,
    required List<int> groupId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleHasGroupConstMeta,
        argValues: [that, groupId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleHasGroupConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_has_group",
        argNames: ["that", "groupId"],
      );

  @override
  Future<PointCryptoHandle> crateApiCryptoPointCryptoHandleNew({
    required String identity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(identity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleNewConstMeta,
        argValues: [identity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleNewConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_new",
        argNames: ["identity"],
      );

  @override
  Future<void> crateApiCryptoPointCryptoHandleProcessCommit({
    required PointCryptoHandle that,
    required List<int> groupId,
    required List<int> commitBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(groupId, serializer);
          sse_encode_list_prim_u_8_loose(commitBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleProcessCommitConstMeta,
        argValues: [that, groupId, commitBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleProcessCommitConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_process_commit",
        argNames: ["that", "groupId", "commitBytes"],
      );

  @override
  Future<Uint8List> crateApiCryptoPointCryptoHandleProcessWelcome({
    required PointCryptoHandle that,
    required List<int> welcomeBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(welcomeBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCryptoPointCryptoHandleProcessWelcomeConstMeta,
        argValues: [that, welcomeBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCryptoPointCryptoHandleProcessWelcomeConstMeta =>
      const TaskConstMeta(
        debugName: "PointCryptoHandle_process_welcome",
        argNames: ["that", "welcomeBytes"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_PointCryptoHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_PointCryptoHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  PointCryptoHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PointCryptoHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PointCryptoHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PointCryptoHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeAddMemberResult dco_decode_bridge_add_member_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeAddMemberResult(
      welcome: dco_decode_list_prim_u_8_strict(arr[0]),
      commit: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  PointCryptoHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PointCryptoHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PointCryptoHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  PointCryptoHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PointCryptoHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeAddMemberResult sse_decode_bridge_add_member_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_welcome = sse_decode_list_prim_u_8_strict(deserializer);
    var var_commit = sse_decode_list_prim_u_8_strict(deserializer);
    return BridgeAddMemberResult(welcome: var_welcome, commit: var_commit);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    PointCryptoHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointCryptoHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    PointCryptoHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointCryptoHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    PointCryptoHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointCryptoHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPointCryptoHandle(
    PointCryptoHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PointCryptoHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bridge_add_member_result(
    BridgeAddMemberResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.welcome, serializer);
    sse_encode_list_prim_u_8_strict(self.commit, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class PointCryptoHandleImpl extends RustOpaque implements PointCryptoHandle {
  // Not to be used by end users
  PointCryptoHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PointCryptoHandleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PointCryptoHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PointCryptoHandle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_PointCryptoHandlePtr,
  );

  /// Add a member to a group using their serialized KeyPackage.
  /// Returns Welcome (for new member) and Commit (for existing members).
  Future<BridgeAddMemberResult> addMember({
    required List<int> groupId,
    required List<int> keyPackageBytes,
  }) => RustLib.instance.api.crateApiCryptoPointCryptoHandleAddMember(
    that: this,
    groupId: groupId,
    keyPackageBytes: keyPackageBytes,
  );

  /// Create a new MLS group. Returns the group ID bytes.
  Future<Uint8List> createGroup({required List<int> groupId}) => RustLib
      .instance
      .api
      .crateApiCryptoPointCryptoHandleCreateGroup(that: this, groupId: groupId);

  /// Decrypt ciphertext from a group. Returns plaintext bytes.
  Future<Uint8List> decrypt({
    required List<int> groupId,
    required List<int> ciphertext,
  }) => RustLib.instance.api.crateApiCryptoPointCryptoHandleDecrypt(
    that: this,
    groupId: groupId,
    ciphertext: ciphertext,
  );

  /// Encrypt plaintext for a group. Returns ciphertext bytes.
  Future<Uint8List> encrypt({
    required List<int> groupId,
    required List<int> plaintext,
  }) => RustLib.instance.api.crateApiCryptoPointCryptoHandleEncrypt(
    that: this,
    groupId: groupId,
    plaintext: plaintext,
  );

  /// Generate a serialized KeyPackage for key exchange.
  /// Upload this to the server so others can add you to groups.
  Future<Uint8List> generateKeyPackage() => RustLib.instance.api
      .crateApiCryptoPointCryptoHandleGenerateKeyPackage(that: this);

  /// Get the number of members in a group.
  Future<BigInt> groupMemberCount({required List<int> groupId}) =>
      RustLib.instance.api.crateApiCryptoPointCryptoHandleGroupMemberCount(
        that: this,
        groupId: groupId,
      );

  /// Check if this instance has joined a specific group.
  bool hasGroup({required List<int> groupId}) => RustLib.instance.api
      .crateApiCryptoPointCryptoHandleHasGroup(that: this, groupId: groupId);

  /// Process an MLS Commit message to stay in sync with group epoch changes.
  Future<void> processCommit({
    required List<int> groupId,
    required List<int> commitBytes,
  }) => RustLib.instance.api.crateApiCryptoPointCryptoHandleProcessCommit(
    that: this,
    groupId: groupId,
    commitBytes: commitBytes,
  );

  /// Process a Welcome message to join a group. Returns the group ID bytes.
  Future<Uint8List> processWelcome({required List<int> welcomeBytes}) =>
      RustLib.instance.api.crateApiCryptoPointCryptoHandleProcessWelcome(
        that: this,
        welcomeBytes: welcomeBytes,
      );
}
